name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: docker login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        PASSWORD_DOCK: ${{ secrets.PASSWORD_DOCK}}
      run: |
        docker login -u $DOCKER_USER -p $PASSWORD_DOCK
    - name: build docker image 
      run : |
        docker build -t kevin2402/docker-graphql:0.0.2  .
    - name: push docker image 
      run : |
        docker push kevin2402/docker-graphql:0.0.2
    
      
       

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
